apiVersion: v1
kind: Secret
metadata:
  name: common-settings
data:
  username: YWRtaW4=
  password: VExad0E0U216NDdacDFJWEM1NnVvb3NBTlQwRUxLam8=
  url: Y3BkLWNwNGkubXljbHVzdGVyLWpwLXRvay0yLTg4MDcwNy1iOWIyYzU1NjNhMjI0MDBkMTRiMjBlZjc1MWFjZThkNS0wMDAwLmpwLXRvay5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZA==
  cloudType: aWJtY2xvdWQ=
  offlineInstall: ZmFsc2U=
  fileStorage: aW50ZWdyYXRpb24tc3RvcmFnZQ==
  blockStorage: aWJtYy12cGMtYmxvY2stZ2VuZXJhbC1wdXJwb3Nl  
---
apiVersion: v1
data:
  password: Z2hwX1dCazNlUlJ2Y2lXdnJmZnZMNkgxOGFuem1tSklCVDJhWjVJcg==
  username: cGhhaXRob29uYQ==
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0:  image-registry.openshift-image-registry.svc:5000
type: kubernetes.io/basic-auth
stringData:
  username: apikey
  password: ZD5Wwux067eD7xc9MiMdPhSRmdJdLYU5g6uuVTPIdeFa
